version: '3.0'

networks:
  foodapi_network:
    external: true

services:
  tank-server:
    image: edikgoose/yandex-tank-api:latest
    container_name: tank
#    network_mode: host
    dns: 8.8.8.8
    depends_on:
      - influx
      - grafana
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}/tests:/var/loadtest
    networks: &network
      - foodapi_network

  influx:
    image: influxdb:1.8
    container_name: influx
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: metrics
    networks: *network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    dns: 8.8.8.8
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning/
      - ${PWD}/grafana/data/dashboards:/var/lib/grafana/dashboards/
      - ${PWD}/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_INFLUX_DB_URL: http://influx:8086
    restart: on-failure
    networks: *network

  postgresql:
    image: postgres:12
    container_name: load-generator-postgres
    ports:
      - "5421:5432"
    environment:
      - POSTGRES_DB=load_generator_adapter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks: *network

  load-generator-adapter:
    image: edikgoose/load-generator-adapter:latest
    container_name: load-generator-adapter
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "8087:8087"
    networks: *network

  consul:
    image: hashicorp/consul:1.18
    container_name: consul-test
    hostname: localhost
    ports:
      - "8500:8500"
    networks: *network
