server:
  port: 8084

spring:
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 20
        generate_statistics: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
    drop-first: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5421/load_generator_adapter
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10

load-generator-engine:
  yandex-tank:
    base-url: http://localhost:8888

  grafana:
    base-url: http://localhost:3001


