server:
  port: 8087

spring:
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 20
        generate_statistics: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
#    drop-first: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://load-generator-postgres:5432/load_generator_adapter}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request_size: 215MB
      file-size-threshold: 2KB


file:
  upload-dir: ${FILE_UPLOAD_DIR:files}


load-generator-engine:
  yandex-tank:
    base-url: ${YANDEX_TANK_BASE_URL:http://tank-server:8888}

  grafana:
    base-url: ${GRAFANA_BASE_URL:http://grafana:3000}
    username: ${GRAFANA_USERNAME:admin}
    password: ${GRAFANA_PASSWORD:admin}


