apiVersion: 1

deleteDatasources:
  - name: Influx
    orgId: 1

datasources:
  - name: Influx
    type: influxdb
    access: proxy
    orgId: 1
    url: ${GF_INFLUX_DB_URL}
    database: metrics
    isDefault: true
    editable: false
