{
 "title": "Overload_{id}",
 "description": "Overload dashboard for yandex tank",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "id" }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "select": [
      [
       { "params": [ "200" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fail responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "query": "SELECT mean(\"0\") FROM \"autogen\".\"proto_codes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "query": "SELECT mean(\"404\")  FROM \"autogen\".\"proto_codes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "500" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timeout responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "query": "SELECT mean(\"504\") FROM \"autogen\".\"proto_codes\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "504" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Not found responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "query": "SELECT mean(\"0\") FROM \"autogen\".\"proto_codes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "404" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redirect responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "query": "SELECT mean(\"0\") FROM \"autogen\".\"proto_codes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "301" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bad gateway responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "query": "SELECT mean(\"0\") FROM \"autogen\".\"proto_codes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "502" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_overall_quantiles",
     "query": "SELECT median(\"q100\") AS \"q100\", mean(\"q99\") AS \"q99\", mean(\"q98\") AS \"q98\", mean(\"q95\") AS \"q95\", mean(\"q90\") AS \"q90\", mean(\"q85\") AS \"q85\", mean(\"q80\") AS \"q80\", mean(\"q75\") AS \"q75\", mean(\"q50\") AS \"q50\" FROM \"autogen\".\"{id}_overall_quantiles\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "q100" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "q100" ], "type": "alias" }
      ],
      [
       { "params": [ "q99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q99" ], "type": "alias" }
      ],
      [
       { "params": [ "q98" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q98" ], "type": "alias" }
      ],
      [
       { "params": [ "q95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q95" ], "type": "alias" }
      ],
      [
       { "params": [ "q90" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q90" ], "type": "alias" }
      ],
      [
       { "params": [ "q85" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q85" ], "type": "alias" }
      ],
      [
       { "params": [ "q80" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q80" ], "type": "alias" }
      ],
      [
       { "params": [ "q75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q75" ], "type": "alias" }
      ],
      [
       { "params": [ "q50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "q50" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "RPS" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_overall_meta",
     "select": [
      [
       { "params": [ "active_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_proto_codes",
     "select": [
      [
       { "params": [ "200" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_200" ], "type": "alias" }
      ],
      [
       { "params": [ "404" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_404" ], "type": "alias" }
      ],
      [
       { "params": [ "500" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_500" ], "type": "alias" }
      ],
      [
       { "params": [ "504" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_504" ], "type": "alias" }
      ],
      [
       { "params": [ "301" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_301" ], "type": "alias" }
      ],
      [
       { "params": [ "302" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_302" ], "type": "alias" }
      ],
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "http_0" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_net_codes",
     "select": [
      [
       { "params": [ "0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "net_0" ], "type": "alias" }
      ],
      [
       { "params": [ "110" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "net_110" ], "type": "alias" }
      ],
      [
       { "params": [ "104" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "net_104" ], "type": "alias" }
      ],
      [
       { "params": [ "OK" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "{id}_overall_meta",
     "select": [
      [
       { "params": [ "RPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}